// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212173505_UpdateTeamMemberNames")]
    partial class UpdateTeamMemberNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApi.Data.Entities.AboutInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReleaseDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Team")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AboutInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductDescription = "A rewards platform where sponsor companies award points to truck drivers for good driving behavior, redeemable for products from a sponsor-managed catalog.",
                            ProductName = "DrivePoints",
                            ReleaseDateUtc = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Team = 14,
                            Version = 2
                        });
                });

            modelBuilder.Entity("WebApi.Data.Entities.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AboutInfoId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AboutInfoId");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutInfoId = 1,
                            Description = "Drivers earn points for safe driving behavior, redeemable for real products from sponsor catalogs.",
                            DisplayOrder = 1,
                            Icon = "trophy",
                            Title = "Points & Rewards"
                        },
                        new
                        {
                            Id = 2,
                            AboutInfoId = 1,
                            Description = "Each sponsor manages a curated product catalog with real-time pricing from external APIs.",
                            DisplayOrder = 2,
                            Icon = "store",
                            Title = "Sponsor Catalogs"
                        },
                        new
                        {
                            Id = 3,
                            AboutInfoId = 1,
                            Description = "Comprehensive reports for sponsors and admins — track points, sales, and driver activity.",
                            DisplayOrder = 3,
                            Icon = "bar-chart-3",
                            Title = "Reporting & Analytics"
                        },
                        new
                        {
                            Id = 4,
                            AboutInfoId = 1,
                            Description = "Enterprise-grade security with encrypted data, audit logging, and role-based access control.",
                            DisplayOrder = 4,
                            Icon = "shield-check",
                            Title = "Security & Trust"
                        });
                });

            modelBuilder.Entity("WebApi.Data.Entities.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AboutInfoId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AboutInfoId");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutInfoId = 1,
                            DisplayOrder = 1,
                            FirstName = "Ben",
                            LastName = "Nazaruk",
                            Role = "Team Lead"
                        },
                        new
                        {
                            Id = 2,
                            AboutInfoId = 1,
                            DisplayOrder = 2,
                            FirstName = "Stella",
                            LastName = "Herzberg",
                            Role = "Software Engineer"
                        },
                        new
                        {
                            Id = 3,
                            AboutInfoId = 1,
                            DisplayOrder = 3,
                            FirstName = "Ella",
                            LastName = "Patel",
                            Role = "Software Engineer"
                        },
                        new
                        {
                            Id = 4,
                            AboutInfoId = 1,
                            DisplayOrder = 4,
                            FirstName = "Trey",
                            LastName = "Larkins",
                            Role = "Software Engineer"
                        });
                });

            modelBuilder.Entity("WebApi.Data.Entities.TechStackItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AboutInfoId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AboutInfoId");

                    b.ToTable("TechStackItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutInfoId = 1,
                            Category = "Frontend",
                            DisplayOrder = 1,
                            Name = "React 19"
                        },
                        new
                        {
                            Id = 2,
                            AboutInfoId = 1,
                            Category = "Frontend",
                            DisplayOrder = 2,
                            Name = "React Router 7"
                        },
                        new
                        {
                            Id = 3,
                            AboutInfoId = 1,
                            Category = "Frontend",
                            DisplayOrder = 3,
                            Name = "React Query"
                        },
                        new
                        {
                            Id = 4,
                            AboutInfoId = 1,
                            Category = "Frontend",
                            DisplayOrder = 4,
                            Name = "Vite 7"
                        },
                        new
                        {
                            Id = 5,
                            AboutInfoId = 1,
                            Category = "Frontend",
                            DisplayOrder = 5,
                            Name = "SCSS Modules"
                        },
                        new
                        {
                            Id = 6,
                            AboutInfoId = 1,
                            Category = "Backend",
                            DisplayOrder = 1,
                            Name = "ASP.NET Core 10"
                        },
                        new
                        {
                            Id = 7,
                            AboutInfoId = 1,
                            Category = "Backend",
                            DisplayOrder = 2,
                            Name = "EF Core 10"
                        },
                        new
                        {
                            Id = 8,
                            AboutInfoId = 1,
                            Category = "Backend",
                            DisplayOrder = 3,
                            Name = "C# 14"
                        },
                        new
                        {
                            Id = 9,
                            AboutInfoId = 1,
                            Category = "Database",
                            DisplayOrder = 1,
                            Name = "MySQL 8"
                        },
                        new
                        {
                            Id = 10,
                            AboutInfoId = 1,
                            Category = "Cloud",
                            DisplayOrder = 1,
                            Name = "AWS EC2"
                        },
                        new
                        {
                            Id = 11,
                            AboutInfoId = 1,
                            Category = "CI/CD",
                            DisplayOrder = 1,
                            Name = "GitHub Actions"
                        });
                });

            modelBuilder.Entity("WebApi.Data.Entities.Feature", b =>
                {
                    b.HasOne("WebApi.Data.Entities.AboutInfo", "AboutInfo")
                        .WithMany("Features")
                        .HasForeignKey("AboutInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AboutInfo");
                });

            modelBuilder.Entity("WebApi.Data.Entities.TeamMember", b =>
                {
                    b.HasOne("WebApi.Data.Entities.AboutInfo", "AboutInfo")
                        .WithMany("TeamMembers")
                        .HasForeignKey("AboutInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AboutInfo");
                });

            modelBuilder.Entity("WebApi.Data.Entities.TechStackItem", b =>
                {
                    b.HasOne("WebApi.Data.Entities.AboutInfo", "AboutInfo")
                        .WithMany("TechStackItems")
                        .HasForeignKey("AboutInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AboutInfo");
                });

            modelBuilder.Entity("WebApi.Data.Entities.AboutInfo", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("TeamMembers");

                    b.Navigation("TechStackItems");
                });
#pragma warning restore 612, 618
        }
    }
}
