// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260411221849_AddAlertSettings")]
    partial class AddAlertSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DriverUserSponsorOrg", b =>
                {
                    b.Property<int>("DriverUserId")
                        .HasColumnType("int");

                    b.Property<int>("SponsorOrgId")
                        .HasColumnType("int");

                    b.HasKey("DriverUserId", "SponsorOrgId");

                    b.HasIndex("SponsorOrgId");

                    b.ToTable("DriverUserSponsorOrg");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebApi.Data.Entities.AboutInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReleaseDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Team")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AboutInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductDescription = "A rewards platform where sponsor companies award points to truck drivers for good driving behavior, redeemable for products from a sponsor-managed catalog.",
                            ProductName = "DrivePoints",
                            ReleaseDateUtc = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Team = 14,
                            Version = 5
                        });
                });

            modelBuilder.Entity("WebApi.Data.Entities.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("WebApi.Data.Entities.Catalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("SponsorOrgId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SponsorOrgId")
                        .IsUnique();

                    b.ToTable("Catalogs");
                });

            modelBuilder.Entity("WebApi.Data.Entities.CatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CachedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CatalogId")
                        .HasColumnType("int");

                    b.Property<decimal>("CatalogPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ExternalId")
                        .HasColumnType("int");

                    b.Property<decimal>("ExternalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId", "ExternalId")
                        .IsUnique();

                    b.ToTable("CatalogItems");
                });

            modelBuilder.Entity("WebApi.Data.Entities.DriverAlertSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOrderAlertsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPointChangeAlertsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSponsorshipAlertsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("DriverId")
                        .IsUnique();

                    b.ToTable("DriverAlertSettings");
                });

            modelBuilder.Entity("WebApi.Data.Entities.DriverApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("date");

                    b.Property<int?>("DriverUserId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("LicensePlate")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool?>("PreviousEmployee")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("longtext");

                    b.Property<int>("SponsorOrgId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TruckMake")
                        .HasColumnType("longtext");

                    b.Property<string>("TruckModel")
                        .HasColumnType("longtext");

                    b.Property<int?>("TruckYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverUserId");

                    b.HasIndex("SponsorOrgId");

                    b.ToTable("DriverApplications");
                });

            modelBuilder.Entity("WebApi.Data.Entities.DriverUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DriverUsers");
                });

            modelBuilder.Entity("WebApi.Data.Entities.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AboutInfoId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AboutInfoId");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutInfoId = 1,
                            Description = "Drivers earn points for safe driving behavior, redeemable for real products from sponsor catalogs.",
                            DisplayOrder = 1,
                            Icon = "trophy",
                            Title = "Points & Rewards"
                        },
                        new
                        {
                            Id = 2,
                            AboutInfoId = 1,
                            Description = "Each sponsor manages a curated product catalog with real-time pricing from external APIs.",
                            DisplayOrder = 2,
                            Icon = "store",
                            Title = "Sponsor Catalogs"
                        },
                        new
                        {
                            Id = 3,
                            AboutInfoId = 1,
                            Description = "Comprehensive reports for sponsors and admins — track points, sales, and driver activity.",
                            DisplayOrder = 3,
                            Icon = "bar-chart-3",
                            Title = "Reporting & Analytics"
                        },
                        new
                        {
                            Id = 4,
                            AboutInfoId = 1,
                            Description = "Enterprise-grade security with encrypted data, audit logging, and role-based access control.",
                            DisplayOrder = 4,
                            Icon = "shield-check",
                            Title = "Security & Trust"
                        });
                });

            modelBuilder.Entity("WebApi.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CanceledDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeliveryCompleteDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeliveryStartDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRefunded")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("PlacedDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ShippedDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SponsorOrgId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("SponsorOrgId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebApi.Data.Entities.OrderAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderAlerts");
                });

            modelBuilder.Entity("WebApi.Data.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PricePoints")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceUsd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("VendorPriceUsd")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("WebApi.Data.Entities.PointRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BalanceChange")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SponsorOrgId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SponsorOrgId");

                    b.ToTable("PointRules");
                });

            modelBuilder.Entity("WebApi.Data.Entities.PointTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BalanceChange")
                        .HasColumnType("int");

                    b.Property<int>("DriverUserId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SponsorOrgId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDateUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DriverUserId");

                    b.HasIndex("SponsorOrgId");

                    b.ToTable("PointTransactions");
                });

            modelBuilder.Entity("WebApi.Data.Entities.PointTransactionAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("TransactionId");

                    b.ToTable("PointTransactionAlerts");
                });

            modelBuilder.Entity("WebApi.Data.Entities.SponsorOrg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PointRatio")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("SponsorName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("SponsorName")
                        .IsUnique();

                    b.ToTable("SponsorOrgs");
                });

            modelBuilder.Entity("WebApi.Data.Entities.SponsorUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("SponsorOrgId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("SponsorOrgId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SponsorUsers");
                });

            modelBuilder.Entity("WebApi.Data.Entities.SponsorshipChangeAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ChangeType")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("SponsorOrgId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("SponsorOrgId");

                    b.ToTable("SponsorshipChangeAlerts");
                });

            modelBuilder.Entity("WebApi.Data.Entities.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AboutInfoId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AboutInfoId");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutInfoId = 1,
                            DisplayOrder = 1,
                            FirstName = "Ben",
                            LastName = "Nazaruk",
                            Role = "Team Lead"
                        },
                        new
                        {
                            Id = 2,
                            AboutInfoId = 1,
                            DisplayOrder = 2,
                            FirstName = "Stella",
                            LastName = "Herzberg",
                            Role = "Software Engineer"
                        },
                        new
                        {
                            Id = 3,
                            AboutInfoId = 1,
                            DisplayOrder = 3,
                            FirstName = "Ella",
                            LastName = "Patel",
                            Role = "Software Engineer"
                        },
                        new
                        {
                            Id = 4,
                            AboutInfoId = 1,
                            DisplayOrder = 4,
                            FirstName = "Trey",
                            LastName = "Larkins",
                            Role = "Software Engineer"
                        });
                });

            modelBuilder.Entity("WebApi.Data.Entities.TechStackItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AboutInfoId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AboutInfoId");

                    b.ToTable("TechStackItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutInfoId = 1,
                            Category = "Frontend",
                            DisplayOrder = 1,
                            Name = "React 19"
                        },
                        new
                        {
                            Id = 2,
                            AboutInfoId = 1,
                            Category = "Frontend",
                            DisplayOrder = 2,
                            Name = "React Router 7"
                        },
                        new
                        {
                            Id = 3,
                            AboutInfoId = 1,
                            Category = "Frontend",
                            DisplayOrder = 3,
                            Name = "React Query"
                        },
                        new
                        {
                            Id = 4,
                            AboutInfoId = 1,
                            Category = "Frontend",
                            DisplayOrder = 4,
                            Name = "Vite 7"
                        },
                        new
                        {
                            Id = 5,
                            AboutInfoId = 1,
                            Category = "Frontend",
                            DisplayOrder = 5,
                            Name = "SCSS Modules"
                        },
                        new
                        {
                            Id = 6,
                            AboutInfoId = 1,
                            Category = "Backend",
                            DisplayOrder = 1,
                            Name = "ASP.NET Core 10"
                        },
                        new
                        {
                            Id = 7,
                            AboutInfoId = 1,
                            Category = "Backend",
                            DisplayOrder = 2,
                            Name = "EF Core 10"
                        },
                        new
                        {
                            Id = 8,
                            AboutInfoId = 1,
                            Category = "Backend",
                            DisplayOrder = 3,
                            Name = "C# 14"
                        },
                        new
                        {
                            Id = 9,
                            AboutInfoId = 1,
                            Category = "Database",
                            DisplayOrder = 1,
                            Name = "MySQL 8"
                        },
                        new
                        {
                            Id = 10,
                            AboutInfoId = 1,
                            Category = "Cloud",
                            DisplayOrder = 1,
                            Name = "AWS EC2"
                        },
                        new
                        {
                            Id = 11,
                            AboutInfoId = 1,
                            Category = "CI/CD",
                            DisplayOrder = 1,
                            Name = "GitHub Actions"
                        });
                });

            modelBuilder.Entity("WebApi.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDateUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("FirstName");

                    b.HasIndex("LastName");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DriverUserSponsorOrg", b =>
                {
                    b.HasOne("WebApi.Data.Entities.DriverUser", null)
                        .WithMany()
                        .HasForeignKey("DriverUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Data.Entities.SponsorOrg", null)
                        .WithMany()
                        .HasForeignKey("SponsorOrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebApi.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebApi.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebApi.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.Data.Entities.AdminUser", b =>
                {
                    b.HasOne("WebApi.Data.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("WebApi.Data.Entities.AdminUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApi.Data.Entities.Catalog", b =>
                {
                    b.HasOne("WebApi.Data.Entities.SponsorOrg", "SponsorOrg")
                        .WithOne("Catalog")
                        .HasForeignKey("WebApi.Data.Entities.Catalog", "SponsorOrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SponsorOrg");
                });

            modelBuilder.Entity("WebApi.Data.Entities.CatalogItem", b =>
                {
                    b.HasOne("WebApi.Data.Entities.Catalog", "Catalog")
                        .WithMany("Items")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("WebApi.Data.Entities.DriverAlertSettings", b =>
                {
                    b.HasOne("WebApi.Data.Entities.DriverUser", "Driver")
                        .WithOne("AlertSettings")
                        .HasForeignKey("WebApi.Data.Entities.DriverAlertSettings", "DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("WebApi.Data.Entities.DriverApplication", b =>
                {
                    b.HasOne("WebApi.Data.Entities.DriverUser", "DriverUser")
                        .WithMany()
                        .HasForeignKey("DriverUserId");

                    b.HasOne("WebApi.Data.Entities.SponsorOrg", "SponsorOrg")
                        .WithMany()
                        .HasForeignKey("SponsorOrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverUser");

                    b.Navigation("SponsorOrg");
                });

            modelBuilder.Entity("WebApi.Data.Entities.DriverUser", b =>
                {
                    b.HasOne("WebApi.Data.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("WebApi.Data.Entities.DriverUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApi.Data.Entities.Feature", b =>
                {
                    b.HasOne("WebApi.Data.Entities.AboutInfo", "AboutInfo")
                        .WithMany("Features")
                        .HasForeignKey("AboutInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AboutInfo");
                });

            modelBuilder.Entity("WebApi.Data.Entities.Order", b =>
                {
                    b.HasOne("WebApi.Data.Entities.DriverUser", "Driver")
                        .WithMany("Orders")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Data.Entities.SponsorOrg", "SponsorOrg")
                        .WithMany()
                        .HasForeignKey("SponsorOrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("SponsorOrg");
                });

            modelBuilder.Entity("WebApi.Data.Entities.OrderAlert", b =>
                {
                    b.HasOne("WebApi.Data.Entities.DriverUser", "Driver")
                        .WithMany("OrderAlerts")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Data.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WebApi.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("WebApi.Data.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WebApi.Data.Entities.PointRule", b =>
                {
                    b.HasOne("WebApi.Data.Entities.SponsorOrg", "SponsorOrg")
                        .WithMany("PointRules")
                        .HasForeignKey("SponsorOrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SponsorOrg");
                });

            modelBuilder.Entity("WebApi.Data.Entities.PointTransaction", b =>
                {
                    b.HasOne("WebApi.Data.Entities.DriverUser", "DriverUser")
                        .WithMany("PointTransactions")
                        .HasForeignKey("DriverUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Data.Entities.SponsorOrg", "SponsorOrg")
                        .WithMany()
                        .HasForeignKey("SponsorOrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverUser");

                    b.Navigation("SponsorOrg");
                });

            modelBuilder.Entity("WebApi.Data.Entities.PointTransactionAlert", b =>
                {
                    b.HasOne("WebApi.Data.Entities.DriverUser", "Driver")
                        .WithMany("PointTransactionAlerts")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Data.Entities.PointTransaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("WebApi.Data.Entities.SponsorUser", b =>
                {
                    b.HasOne("WebApi.Data.Entities.SponsorOrg", "SponsorOrg")
                        .WithMany("SponsorUsers")
                        .HasForeignKey("SponsorOrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Data.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("WebApi.Data.Entities.SponsorUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SponsorOrg");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApi.Data.Entities.SponsorshipChangeAlert", b =>
                {
                    b.HasOne("WebApi.Data.Entities.DriverUser", "Driver")
                        .WithMany("SponsorshipChangeAlerts")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Data.Entities.SponsorOrg", "SponsorOrg")
                        .WithMany()
                        .HasForeignKey("SponsorOrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("SponsorOrg");
                });

            modelBuilder.Entity("WebApi.Data.Entities.TeamMember", b =>
                {
                    b.HasOne("WebApi.Data.Entities.AboutInfo", "AboutInfo")
                        .WithMany("TeamMembers")
                        .HasForeignKey("AboutInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AboutInfo");
                });

            modelBuilder.Entity("WebApi.Data.Entities.TechStackItem", b =>
                {
                    b.HasOne("WebApi.Data.Entities.AboutInfo", "AboutInfo")
                        .WithMany("TechStackItems")
                        .HasForeignKey("AboutInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AboutInfo");
                });

            modelBuilder.Entity("WebApi.Data.Entities.AboutInfo", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("TeamMembers");

                    b.Navigation("TechStackItems");
                });

            modelBuilder.Entity("WebApi.Data.Entities.Catalog", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("WebApi.Data.Entities.DriverUser", b =>
                {
                    b.Navigation("AlertSettings");

                    b.Navigation("OrderAlerts");

                    b.Navigation("Orders");

                    b.Navigation("PointTransactionAlerts");

                    b.Navigation("PointTransactions");

                    b.Navigation("SponsorshipChangeAlerts");
                });

            modelBuilder.Entity("WebApi.Data.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("WebApi.Data.Entities.SponsorOrg", b =>
                {
                    b.Navigation("Catalog")
                        .IsRequired();

                    b.Navigation("PointRules");

                    b.Navigation("SponsorUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
